# instrument model naming is inconsistent.
# I had to remap some names to instanciate the class that represents that model
correct_names = {"PCIE_1751": "Advantech_PCIE_1751",
                 "E8267C": "E8267",
                 "E8527D": "Agilent_E8527D",
                 "HP33210A": "Agilent_HP33210A",
                 "ATS": "AlazarTech_ATS",
                 "ATS9870": "AlazarTech_ATS9870",
                 "ATS_acquisition_controllers": "Demodulation_AcquisitionController",
                 "KeysightAgilent_33XXX": "WaveformGenerator_33XXX",
                 "Base_SPDT": "SPDT_Base",
                 "ILM200": "OxfordInstruments_ILM200",
                 "IPS120": "OxfordInstruments_IPS120",
                 "QDac_channels": "QDac",
                 "DG4000": "Rigol_DG4000",
                 "SGS100A": "RohdeSchwarz_SGS100A",
                 "SMR40": "RohdeSchwarz_SMR40",
                 "USB_SA124B": "SignalHound_USB_SA124B",
                 "SG384": "SRS_SG384",
                 "AWG5014": "Tektronix_AWG5014",
                 "AWG520": "Tektronix_AWG520",
                 "AWG5200": "Tektronix_AWG5200",
                 "Keithley_2600_channels": "Keithley_2600",
				 "DAC20bit": "IST_20"
                 }